/**
 * antd 再导出面（00-governance D8）：业务代码唯一的 UI 来源。
 * 只导出本系统实际使用的组件面，新组件先在此登记。
 */

export {
  BellOutlined,
  BulbOutlined,
  CheckOutlined,
  CloseOutlined,
  DashboardOutlined,
  DesktopOutlined,
  ExperimentOutlined,
  FileTextOutlined,
  GlobalOutlined,
  LogoutOutlined,
  MenuFoldOutlined,
  MenuUnfoldOutlined,
  MoonOutlined,
  ProductOutlined,
  ProjectOutlined,
  SearchOutlined,
  SettingOutlined,
  SunOutlined,
  TeamOutlined,
  UserOutlined,
} from '@ant-design/icons'
export type { MenuProps, ModalProps, TableColumnsType, TableProps, TabsProps, ThemeConfig } from 'antd'
export {
  Alert,
  App as AppProvider,
  AutoComplete,
  Avatar,
  Badge,
  Button,
  Card,
  Checkbox,
  ConfigProvider,
  DatePicker,
  Descriptions,
  Divider,
  Drawer,
  Dropdown,
  Empty,
  Flex,
  Form,
  Input,
  InputNumber,
  Layout,
  List,
  Menu,
  Popconfirm,
  Popover,
  Progress,
  Radio,
  Result,
  Segmented,
  Select,
  Space,
  Spin,
  Statistic,
  Switch,
  Table,
  Tabs,
  Tag,
  Tooltip,
  Tree,
  TreeSelect,
  Typography,
  theme,
  Upload,
} from 'antd'
