// 域出口白名单（01 §3.2）：跨域只准 import 本文件。

export type {
  ActivityPage,
  BatchResultItem,
  DocCategoryNode,
  DocSpaceView,
  DocVersionView,
  DocView,
  FileView,
  ListResult,
} from './api/doc.api'
export {
  DOC_QUERY_ROOTS,
  deleteDocAction,
  fetchDoc,
  fetchDocActivities,
  fetchDocCategories,
  fetchDocFiles,
  fetchDocMeta,
  fetchDocSpace,
  fetchDocSpaceMeta,
  fetchDocSpaces,
  fetchDocs,
  fetchDocVersion,
  fetchDocVersions,
  fetchSpaceDocs,
  moveDocAction,
  patchDoc,
  patchDocSpace,
  publishDocAction,
  qk,
  saveDocDraftAction,
  submitBatchDocs,
  submitDoc,
  submitDocSpace,
  TREE_LIMIT,
} from './api/doc.api'
export { MarkdownView } from './components/markdown-view'
export {
  buildDocTree,
  DOC_ACLS,
  DOC_MY_TABS,
  DOC_SPACE_ACLS,
  DOC_SPACE_TYPES,
  DOC_STATUSES,
  DOC_TYPES,
  type DocMyTab,
  type DocNode,
  docAclKey,
  docCountByCategory,
  docExcerpt,
  docSpaceAclKey,
  docSpaceTypeKey,
  docStatusKey,
  docStatusTone,
  docTypeKey,
  flattenCategories,
  myDocFilters,
  showDraftBadge,
} from './model'
