/**
 * AUTO-GENERATED by tools/route-codegen.mjs — 禁止手改（01 §3.4），改页面注解后执行 pnpm routes 重新生成。
 * 注解字段：@route/@title/@perm/@menu/@order/@icon/@hide/@activeMenu（06 A1-1）。
 */
import { PageLoading } from '@zentao/design-system'
import { lazy, type ReactNode, Suspense } from 'react'
import type { RouteObject } from 'react-router'

export type NavigationItem = { path: string; title: string; perm?: string; icon?: string; order: number }
export type NavigationSection = { key: string; title: string; order: number; children: NavigationItem[] }
export type NavigationGroup = {
  key: string
  title: string
  icon?: string
  children: (NavigationItem | NavigationSection)[]
}

const AuditLogListPage = lazy(() => import('../features/platform/pages/audit-log-list-page.page'))
const LangItemPage = lazy(() => import('../features/platform/pages/lang-item-page.page'))
const LangUploadPage = lazy(() => import('../features/platform/pages/lang-upload-page.page'))
const LoginLogListPage = lazy(() => import('../features/platform/pages/login-log-list-page.page'))
const RoleListPage = lazy(() => import('../features/org/pages/role-list-page.page'))
const SettingPage = lazy(() => import('../features/platform/pages/setting-page.page'))
const BoardSpaceListPage = lazy(() => import('../features/board/pages/board-space-list-page.page'))
const BoardSpaceDetailPage = lazy(() => import('../features/board/pages/board-space-detail-page.page'))
const BoardPage = lazy(() => import('../features/board/pages/board-page.page'))
const BugDetailPage = lazy(() => import('../features/quality/pages/bug-detail-page.page'))
const BugBatchEditPage = lazy(() => import('../features/quality/pages/bug-batch-edit-page.page'))
const BuildDetailPage = lazy(() => import('../features/product/pages/build-detail-page.page'))
const DocFilesPage = lazy(() => import('../features/doc/pages/doc-files-page.page'))
const DocMyPage = lazy(() => import('../features/doc/pages/doc-my-page.page'))
const DocSpaceListPage = lazy(() => import('../features/doc/pages/doc-space-list-page.page'))
const DocSpacePage = lazy(() => import('../features/doc/pages/doc-space-page.page'))
const DocDetailPage = lazy(() => import('../features/doc/pages/doc-detail-page.page'))
const DocDiffPage = lazy(() => import('../features/doc/pages/doc-diff-page.page'))
const DocEditPage = lazy(() => import('../features/doc/pages/doc-edit-page.page'))
const DocVersionsPage = lazy(() => import('../features/doc/pages/doc-versions-page.page'))
const ExecutionListPage = lazy(() => import('../features/project/pages/execution-list-page.page'))
const ExecutionDetailPage = lazy(() => import('../features/project/pages/execution-detail-page.page'))
const ExecutionKanbanPage = lazy(() => import('../features/project/pages/execution-kanban-page.page'))
const ReportListPage = lazy(() => import('../features/quality/pages/report-list-page.page'))
const ReportBurnPage = lazy(() => import('../features/workspace/pages/report-burn-page.page'))
const TaskListPage = lazy(() => import('../features/task/pages/task-list-page.page'))
const TaskBatchCreatePage = lazy(() => import('../features/task/pages/task-batch-create-page.page'))
const LibraryListPage = lazy(() => import('../features/quality/pages/library-list-page.page'))
const LibraryDetailPage = lazy(() => import('../features/quality/pages/library-detail-page.page'))
const LibraryCaseBatchCreatePage = lazy(() => import('../features/quality/pages/library-case-batch-create-page.page'))
const LoginPage = lazy(() => import('../features/auth/pages/login-page.page'))
const MyDashboardPage = lazy(() => import('../features/workspace/pages/my-dashboard-page.page'))
const MyActivitiesPage = lazy(() => import('../features/workspace/pages/my-activities-page.page'))
const MyBugsPage = lazy(() => import('../features/workspace/pages/my-bugs-page.page'))
const MyProfilePage = lazy(() => import('../features/workspace/pages/my-profile-page.page'))
const MyStoriesPage = lazy(() => import('../features/workspace/pages/my-stories-page.page'))
const MyTasksPage = lazy(() => import('../features/workspace/pages/my-tasks-page.page'))
const TodoListPage = lazy(() => import('../features/workspace/pages/todo-list-page.page'))
const NotificationListPage = lazy(() => import('../features/platform/pages/notification-list-page.page'))
const NotificationSettingPage = lazy(() => import('../features/platform/pages/notification-setting-page.page'))
const AccountListPage = lazy(() => import('../features/org/pages/account-list-page.page'))
const AccountDetailPage = lazy(() => import('../features/org/pages/account-detail-page.page'))
const AccountBatchCreatePage = lazy(() => import('../features/org/pages/account-batch-create-page.page'))
const DepartmentListPage = lazy(() => import('../features/org/pages/department-list-page.page'))
const GroupDetailPage = lazy(() => import('../features/org/pages/group-detail-page.page'))
const GroupPrivMatrixPage = lazy(() => import('../features/org/pages/group-priv-matrix-page.page'))
const PersonnelListPage = lazy(() => import('../features/org/pages/personnel-list-page.page'))
const PersonnelWorkloadPage = lazy(() => import('../features/org/pages/personnel-workload-page.page'))
const PlanDetailPage = lazy(() => import('../features/product/pages/plan-detail-page.page'))
const ProductListPage = lazy(() => import('../features/product/pages/product-list-page.page'))
const ProductDetailPage = lazy(() => import('../features/product/pages/product-detail-page.page'))
const ProductBranchesPage = lazy(() => import('../features/product/pages/product-branches-page.page'))
const BugListPage = lazy(() => import('../features/quality/pages/bug-list-page.page'))
const BugBatchCreatePage = lazy(() => import('../features/quality/pages/bug-batch-create-page.page'))
const BuildListPage = lazy(() => import('../features/product/pages/build-list-page.page'))
const ProductCategoriesPage = lazy(() => import('../features/product/pages/product-categories-page.page'))
const ProductDynamicPage = lazy(() => import('../features/product/pages/product-dynamic-page.page'))
const PlanListPage = lazy(() => import('../features/product/pages/plan-list-page.page'))
const ProductProjectsPage = lazy(() => import('../features/product/pages/product-projects-page.page'))
const ReleaseListPage = lazy(() => import('../features/product/pages/release-list-page.page'))
const ReportBugDistributionPage = lazy(() => import('../features/workspace/pages/report-bug-distribution-page.page'))
const ReportStorySummaryPage = lazy(() => import('../features/workspace/pages/report-story-summary-page.page'))
const StoryListPage = lazy(() => import('../features/story/pages/story-list-page.page'))
const StoryBatchCreatePage = lazy(() => import('../features/story/pages/story-batch-create-page.page'))
const SuiteListPage = lazy(() => import('../features/quality/pages/suite-list-page.page'))
const TestCaseListPage = lazy(() => import('../features/quality/pages/test-case-list-page.page'))
const TestCaseBatchCreatePage = lazy(() => import('../features/quality/pages/test-case-batch-create-page.page'))
const TestRunListPage = lazy(() => import('../features/quality/pages/test-run-list-page.page'))
const ProductTrackPage = lazy(() => import('../features/product/pages/product-track-page.page'))
const ProductBatchEditPage = lazy(() => import('../features/product/pages/product-batch-edit-page.page'))
const ProductKanbanPage = lazy(() => import('../features/product/pages/product-kanban-page.page'))
const ProgramListPage = lazy(() => import('../features/project/pages/program-list-page.page'))
const ProgramDetailPage = lazy(() => import('../features/project/pages/program-detail-page.page'))
const ProjectListPage = lazy(() => import('../features/project/pages/project-list-page.page'))
const ProjectDetailPage = lazy(() => import('../features/project/pages/project-detail-page.page'))
const ProjectExecutionListPage = lazy(() => import('../features/project/pages/project-execution-list-page.page'))
const ProjectMemberPage = lazy(() => import('../features/project/pages/project-member-page.page'))
const ProjectStakeholderPage = lazy(() => import('../features/project/pages/project-stakeholder-page.page'))
const ProjectStoryListPage = lazy(() => import('../features/project/pages/project-story-list-page.page'))
const WeeklyReportPage = lazy(() => import('../features/workspace/pages/weekly-report-page.page'))
const ProjectWhitelistPage = lazy(() => import('../features/project/pages/project-whitelist-page.page'))
const ReleaseDetailPage = lazy(() => import('../features/product/pages/release-detail-page.page'))
const ReportDetailPage = lazy(() => import('../features/quality/pages/report-detail-page.page'))
const StageListPage = lazy(() => import('../features/project/pages/stage-list-page.page'))
const StoryDetailPage = lazy(() => import('../features/story/pages/story-detail-page.page'))
const StoryBatchEditPage = lazy(() => import('../features/story/pages/story-batch-edit-page.page'))
const SuiteDetailPage = lazy(() => import('../features/quality/pages/suite-detail-page.page'))
const TaskDetailPage = lazy(() => import('../features/task/pages/task-detail-page.page'))
const TaskBatchEditPage = lazy(() => import('../features/task/pages/task-batch-edit-page.page'))
const TestCaseDetailPage = lazy(() => import('../features/quality/pages/test-case-detail-page.page'))
const TestCaseBatchEditPage = lazy(() => import('../features/quality/pages/test-case-batch-edit-page.page'))
const TestRunDetailPage = lazy(() => import('../features/quality/pages/test-run-detail-page.page'))
const TestRunCasesPage = lazy(() => import('../features/quality/pages/test-run-cases-page.page'))
const ReportCasePassRatePage = lazy(() => import('../features/workspace/pages/report-case-pass-rate-page.page'))
const TodoDetailPage = lazy(() => import('../features/workspace/pages/todo-detail-page.page'))
const TodoBatchCreatePage = lazy(() => import('../features/workspace/pages/todo-batch-create-page.page'))
const TodoBatchEditPage = lazy(() => import('../features/workspace/pages/todo-batch-edit-page.page'))

const withSuspense = (node: ReactNode) => <Suspense fallback={<PageLoading />}>{node}</Suspense>

export const generatedRoutes: RouteObject[] = [
  {
    path: '/admin/audit-logs',
    element: withSuspense(<AuditLogListPage />),
    handle: { title: 'platform.auditLog.title', perm: 'audit-log-view' },
  },
  {
    path: '/admin/lang-items',
    element: withSuspense(<LangItemPage />),
    handle: { title: 'platform.lang.title', perm: 'lang-manage' },
  },
  {
    path: '/admin/lang-upload',
    element: withSuspense(<LangUploadPage />),
    handle: { title: 'platform.langUpload.title', perm: 'lang-manage' },
  },
  {
    path: '/admin/login-logs',
    element: withSuspense(<LoginLogListPage />),
    handle: { title: 'platform.loginLog.title', perm: 'audit-log-view' },
  },
  {
    path: '/admin/roles',
    element: withSuspense(<RoleListPage />),
    handle: { title: 'org.role.title', perm: 'role-view' },
  },
  {
    path: '/admin/settings',
    element: withSuspense(<SettingPage />),
    handle: { title: 'platform.settings.title', perm: 'setting-manage' },
  },
  {
    path: '/board-spaces',
    element: withSuspense(<BoardSpaceListPage />),
    handle: { title: 'board.title.spaceList', perm: 'board-view' },
  },
  {
    path: '/board-spaces/:boardSpaceId',
    element: withSuspense(<BoardSpaceDetailPage />),
    handle: { title: 'board.title.spaceDetail', perm: 'board-view' },
  },
  {
    path: '/boards/:boardId',
    element: withSuspense(<BoardPage />),
    handle: { title: 'board.title.board', perm: 'board-view' },
  },
  {
    path: '/bugs/:bugId',
    element: withSuspense(<BugDetailPage />),
    handle: { title: 'quality.title.bugDetail', perm: 'bug-view' },
  },
  {
    path: '/bugs/batch-edit',
    element: withSuspense(<BugBatchEditPage />),
    handle: { title: 'quality.title.bugBatchEdit', perm: 'bug-edit' },
  },
  {
    path: '/builds/:buildId',
    element: withSuspense(<BuildDetailPage />),
    handle: { title: 'build.title.detail', perm: 'build-view' },
  },
  {
    path: '/doc/files',
    element: withSuspense(<DocFilesPage />),
    handle: { title: 'doc.title.files', perm: 'doc-view' },
  },
  {
    path: '/doc/my',
    element: withSuspense(<DocMyPage />),
    handle: { title: 'doc.title.my', perm: 'doc-view' },
  },
  {
    path: '/doc/spaces',
    element: withSuspense(<DocSpaceListPage />),
    handle: { title: 'docSpace.title.list', perm: 'doc-space-view' },
  },
  {
    path: '/doc/spaces/:docSpaceId',
    element: withSuspense(<DocSpacePage />),
    handle: { title: 'docSpace.title.detail', perm: 'doc-space-view' },
  },
  {
    path: '/docs/:docId',
    element: withSuspense(<DocDetailPage />),
    handle: { title: 'doc.title.detail', perm: 'doc-view' },
  },
  {
    path: '/docs/:docId/diff',
    element: withSuspense(<DocDiffPage />),
    handle: { title: 'docVersion.title.diff', perm: 'doc-view' },
  },
  {
    path: '/docs/:docId/edit',
    element: withSuspense(<DocEditPage />),
    handle: { title: 'doc.title.edit', perm: 'doc-edit' },
  },
  {
    path: '/docs/:docId/versions',
    element: withSuspense(<DocVersionsPage />),
    handle: { title: 'docVersion.title.list', perm: 'doc-view' },
  },
  {
    path: '/executions',
    element: withSuspense(<ExecutionListPage />),
    handle: { title: 'project.title.executions', perm: 'execution-view' },
  },
  {
    path: '/executions/:executionId',
    element: withSuspense(<ExecutionDetailPage />),
    handle: { title: 'project.title.executionDetail', perm: 'execution-view' },
  },
  {
    path: '/executions/:executionId/kanban',
    element: withSuspense(<ExecutionKanbanPage />),
    handle: { title: 'board.title.executionKanban', perm: 'execution-view' },
  },
  {
    path: '/executions/:executionId/reports',
    element: withSuspense(<ReportListPage />),
    handle: { title: 'quality.title.reports', perm: 'report-view' },
  },
  {
    path: '/executions/:executionId/reports/burn',
    element: withSuspense(<ReportBurnPage />),
    handle: { title: 'report.title.burn', perm: 'report-view' },
  },
  {
    path: '/executions/:executionId/tasks',
    element: withSuspense(<TaskListPage />),
    handle: { title: 'task.title.list', perm: 'task-view' },
  },
  {
    path: '/executions/:executionId/tasks/batch-create',
    element: withSuspense(<TaskBatchCreatePage />),
    handle: { title: 'task.title.batchCreate', perm: 'task-create' },
  },
  {
    path: '/libraries',
    element: withSuspense(<LibraryListPage />),
    handle: { title: 'quality.title.libraries', perm: 'library-view' },
  },
  {
    path: '/libraries/:libraryId',
    element: withSuspense(<LibraryDetailPage />),
    handle: { title: 'quality.title.libraryDetail', perm: 'library-view' },
  },
  {
    path: '/libraries/:libraryId/test-cases/batch',
    element: withSuspense(<LibraryCaseBatchCreatePage />),
    handle: { title: 'quality.title.libraryCaseBatchCreate', perm: 'library-edit' },
  },
  {
    path: '/login',
    element: withSuspense(<LoginPage />),
    handle: { title: 'auth.login.title' },
  },
  {
    path: '/my',
    element: withSuspense(<MyDashboardPage />),
    handle: { title: 'workspace.title.dashboard', perm: 'my-view' },
  },
  {
    path: '/my/activities',
    element: withSuspense(<MyActivitiesPage />),
    handle: { title: 'workspace.title.activities', perm: 'my-view' },
  },
  {
    path: '/my/bugs',
    element: withSuspense(<MyBugsPage />),
    handle: { title: 'workspace.title.myBugs', perm: 'my-view' },
  },
  {
    path: '/my/profile',
    element: withSuspense(<MyProfilePage />),
    handle: { title: 'my.profile.title', perm: 'account-view' },
  },
  {
    path: '/my/stories',
    element: withSuspense(<MyStoriesPage />),
    handle: { title: 'workspace.title.myStories', perm: 'my-view' },
  },
  {
    path: '/my/tasks',
    element: withSuspense(<MyTasksPage />),
    handle: { title: 'workspace.title.myTasks', perm: 'my-view' },
  },
  {
    path: '/my/todos',
    element: withSuspense(<TodoListPage />),
    handle: { title: 'workspace.title.todos', perm: 'todo-view' },
  },
  {
    path: '/notifications',
    element: withSuspense(<NotificationListPage />),
    handle: { title: 'platform.notifications.title' },
  },
  {
    path: '/notifications/settings',
    element: withSuspense(<NotificationSettingPage />),
    handle: { title: 'platform.notification.settings.title' },
  },
  {
    path: '/org/accounts',
    element: withSuspense(<AccountListPage />),
    handle: { title: 'org.accounts.title', perm: 'account-view' },
  },
  {
    path: '/org/accounts/:accountId',
    element: withSuspense(<AccountDetailPage />),
    handle: { title: 'org.account.detailTitle', perm: 'account-view' },
  },
  {
    path: '/org/accounts/batch',
    element: withSuspense(<AccountBatchCreatePage />),
    handle: { title: 'org.accounts.batchTitle', perm: 'account-create' },
  },
  {
    path: '/org/departments',
    element: withSuspense(<DepartmentListPage />),
    handle: { title: 'org.departments.title', perm: 'department-view' },
  },
  {
    path: '/org/groups/:groupId',
    element: withSuspense(<GroupDetailPage />),
    handle: { title: 'org.group.detailTitle', perm: 'group-view' },
  },
  {
    path: '/org/groups/:groupId/privileges',
    element: withSuspense(<GroupPrivMatrixPage />),
    handle: { title: 'org.group.matrixTitle', perm: 'group-priv-edit' },
  },
  {
    path: '/personnel',
    element: withSuspense(<PersonnelListPage />),
    handle: { title: 'personnel.title', perm: 'personnel-view' },
  },
  {
    path: '/personnel/workload',
    element: withSuspense(<PersonnelWorkloadPage />),
    handle: { title: 'personnel.workload.title', perm: 'personnel-view' },
  },
  {
    path: '/plans/:planId',
    element: withSuspense(<PlanDetailPage />),
    handle: { title: 'plan.title.detail', perm: 'plan-view' },
  },
  {
    path: '/products',
    element: withSuspense(<ProductListPage />),
    handle: { title: 'product.title.list', perm: 'product-view' },
  },
  {
    path: '/products/:productId',
    element: withSuspense(<ProductDetailPage />),
    handle: { title: 'product.title.detail', perm: 'product-view' },
  },
  {
    path: '/products/:productId/branches',
    element: withSuspense(<ProductBranchesPage />),
    handle: { title: 'branch.title.list', perm: 'product-view' },
  },
  {
    path: '/products/:productId/bugs',
    element: withSuspense(<BugListPage />),
    handle: { title: 'quality.title.bugs', perm: 'bug-view' },
  },
  {
    path: '/products/:productId/bugs/batch',
    element: withSuspense(<BugBatchCreatePage />),
    handle: { title: 'quality.title.bugBatchCreate', perm: 'bug-create' },
  },
  {
    path: '/products/:productId/builds',
    element: withSuspense(<BuildListPage />),
    handle: { title: 'build.title.list', perm: 'build-view' },
  },
  {
    path: '/products/:productId/categories',
    element: withSuspense(<ProductCategoriesPage />),
    handle: { title: 'category.title.list', perm: 'product-view' },
  },
  {
    path: '/products/:productId/dynamic',
    element: withSuspense(<ProductDynamicPage />),
    handle: { title: 'product.title.dynamic', perm: 'product-view' },
  },
  {
    path: '/products/:productId/plans',
    element: withSuspense(<PlanListPage />),
    handle: { title: 'plan.title.list', perm: 'plan-view' },
  },
  {
    path: '/products/:productId/projects',
    element: withSuspense(<ProductProjectsPage />),
    handle: { title: 'project.title.list', perm: 'project-view' },
  },
  {
    path: '/products/:productId/releases',
    element: withSuspense(<ReleaseListPage />),
    handle: { title: 'release.title.list', perm: 'release-view' },
  },
  {
    path: '/products/:productId/reports/bug-distribution',
    element: withSuspense(<ReportBugDistributionPage />),
    handle: { title: 'report.title.bugDistribution', perm: 'report-view' },
  },
  {
    path: '/products/:productId/reports/story-summary',
    element: withSuspense(<ReportStorySummaryPage />),
    handle: { title: 'report.title.storySummary', perm: 'report-view' },
  },
  {
    path: '/products/:productId/stories',
    element: withSuspense(<StoryListPage />),
    handle: { title: 'story.title.list', perm: 'story-view' },
  },
  {
    path: '/products/:productId/stories/batch',
    element: withSuspense(<StoryBatchCreatePage />),
    handle: { title: 'story.title.batchCreate', perm: 'story-create' },
  },
  {
    path: '/products/:productId/suites',
    element: withSuspense(<SuiteListPage />),
    handle: { title: 'quality.title.suites', perm: 'suite-view' },
  },
  {
    path: '/products/:productId/test-cases',
    element: withSuspense(<TestCaseListPage />),
    handle: { title: 'quality.title.testCases', perm: 'testcase-view' },
  },
  {
    path: '/products/:productId/test-cases/batch',
    element: withSuspense(<TestCaseBatchCreatePage />),
    handle: { title: 'quality.title.caseBatchCreate', perm: 'testcase-create' },
  },
  {
    path: '/products/:productId/test-runs',
    element: withSuspense(<TestRunListPage />),
    handle: { title: 'quality.title.testRuns', perm: 'testrun-view' },
  },
  {
    path: '/products/:productId/track',
    element: withSuspense(<ProductTrackPage />),
    handle: { title: 'product.title.track', perm: 'product-view' },
  },
  {
    path: '/products/batch-edit',
    element: withSuspense(<ProductBatchEditPage />),
    handle: { title: 'product.title.batchEdit', perm: 'product-edit' },
  },
  {
    path: '/products/kanban',
    element: withSuspense(<ProductKanbanPage />),
    handle: { title: 'product.title.kanban', perm: 'product-view' },
  },
  {
    path: '/programs',
    element: withSuspense(<ProgramListPage />),
    handle: { title: 'project.title.programList', perm: 'program-view' },
  },
  {
    path: '/programs/:programId',
    element: withSuspense(<ProgramDetailPage />),
    handle: { title: 'project.title.programDetail', perm: 'program-view' },
  },
  {
    path: '/projects',
    element: withSuspense(<ProjectListPage />),
    handle: { title: 'project.title.list', perm: 'project-view' },
  },
  {
    path: '/projects/:projectId',
    element: withSuspense(<ProjectDetailPage />),
    handle: { title: 'project.title.detail', perm: 'project-view' },
  },
  {
    path: '/projects/:projectId/executions',
    element: withSuspense(<ProjectExecutionListPage />),
    handle: { title: 'project.title.executionList', perm: 'execution-view' },
  },
  {
    path: '/projects/:projectId/members',
    element: withSuspense(<ProjectMemberPage />),
    handle: { title: 'project.title.members', perm: 'project-view' },
  },
  {
    path: '/projects/:projectId/stakeholders',
    element: withSuspense(<ProjectStakeholderPage />),
    handle: { title: 'project.title.stakeholders', perm: 'stakeholder-view' },
  },
  {
    path: '/projects/:projectId/stories',
    element: withSuspense(<ProjectStoryListPage />),
    handle: { title: 'project.title.stories', perm: 'project-view' },
  },
  {
    path: '/projects/:projectId/weekly-report',
    element: withSuspense(<WeeklyReportPage />),
    handle: { title: 'weeklyReport.title', perm: 'weekly-report-view' },
  },
  {
    path: '/projects/:projectId/whitelist',
    element: withSuspense(<ProjectWhitelistPage />),
    handle: { title: 'project.title.whitelist', perm: 'project-view' },
  },
  {
    path: '/releases/:releaseId',
    element: withSuspense(<ReleaseDetailPage />),
    handle: { title: 'release.title.detail', perm: 'release-view' },
  },
  {
    path: '/reports/:reportId',
    element: withSuspense(<ReportDetailPage />),
    handle: { title: 'quality.title.reportDetail', perm: 'report-view' },
  },
  {
    path: '/settings/stages',
    element: withSuspense(<StageListPage />),
    handle: { title: 'stage.title.list', perm: 'stage-view' },
  },
  {
    path: '/stories/:storyId',
    element: withSuspense(<StoryDetailPage />),
    handle: { title: 'story.title.detail', perm: 'story-view' },
  },
  {
    path: '/stories/batch-edit',
    element: withSuspense(<StoryBatchEditPage />),
    handle: { title: 'story.title.batchEdit', perm: 'story-edit' },
  },
  {
    path: '/suites/:suiteId',
    element: withSuspense(<SuiteDetailPage />),
    handle: { title: 'quality.title.suiteDetail', perm: 'suite-view' },
  },
  {
    path: '/tasks/:taskId',
    element: withSuspense(<TaskDetailPage />),
    handle: { title: 'task.title.detail', perm: 'task-view' },
  },
  {
    path: '/tasks/batch-edit',
    element: withSuspense(<TaskBatchEditPage />),
    handle: { title: 'task.title.batchEdit', perm: 'task-edit' },
  },
  {
    path: '/test-cases/:caseId',
    element: withSuspense(<TestCaseDetailPage />),
    handle: { title: 'quality.title.testCaseDetail', perm: 'testcase-view' },
  },
  {
    path: '/test-cases/batch-edit',
    element: withSuspense(<TestCaseBatchEditPage />),
    handle: { title: 'quality.title.caseBatchEdit', perm: 'testcase-edit' },
  },
  {
    path: '/test-runs/:testRunId',
    element: withSuspense(<TestRunDetailPage />),
    handle: { title: 'quality.title.testRunDetail', perm: 'testrun-view' },
  },
  {
    path: '/test-runs/:testRunId/cases',
    element: withSuspense(<TestRunCasesPage />),
    handle: { title: 'quality.title.testRunCases', perm: 'testrun-view' },
  },
  {
    path: '/test-runs/:testRunId/reports/case-pass-rate',
    element: withSuspense(<ReportCasePassRatePage />),
    handle: { title: 'report.title.casePassRate', perm: 'report-view' },
  },
  {
    path: '/todos/:todoId',
    element: withSuspense(<TodoDetailPage />),
    handle: { title: 'workspace.title.todoDetail', perm: 'todo-view' },
  },
  {
    path: '/todos/batch-create',
    element: withSuspense(<TodoBatchCreatePage />),
    handle: { title: 'workspace.title.todoBatchCreate', perm: 'todo-create' },
  },
  {
    path: '/todos/batch-edit',
    element: withSuspense(<TodoBatchEditPage />),
    handle: { title: 'workspace.title.todoBatchEdit', perm: 'todo-edit' },
  },
]

/** 层级导航（菜单/搜索派生源，01 §3.4 + 06 A1-1；分区见 SECTION_META）：组 →（分区 →）项；@hide 页不进树。title 均为 i18n 键。 */
export const navigation: NavigationGroup[] = [
  {
    key: 'dashboard',
    title: 'nav.group.dashboard',
    icon: 'DashboardOutlined',
    children: [
      { path: '/my', title: 'workspace.title.dashboard', order: 1, perm: 'my-view' },
      { path: '/my/todos', title: 'workspace.title.todos', order: 2, perm: 'todo-view' },
      { path: '/my/tasks', title: 'workspace.title.myTasks', order: 3, perm: 'my-view' },
      { path: '/my/bugs', title: 'workspace.title.myBugs', order: 4, perm: 'my-view' },
      { path: '/my/stories', title: 'workspace.title.myStories', order: 5, perm: 'my-view' },
      { path: '/my/activities', title: 'workspace.title.activities', order: 6, perm: 'my-view' },
      { path: '/notifications', title: 'platform.notifications.title', order: 7 },
    ],
  },
  {
    key: 'product',
    title: 'nav.group.product',
    icon: 'ProductOutlined',
    children: [
      { path: '/products', title: 'product.title.list', order: 1, perm: 'product-view' },
      { path: '/products/kanban', title: 'product.title.kanban', order: 2, perm: 'product-view' },
    ],
  },
  {
    key: 'project',
    title: 'nav.group.project',
    icon: 'ProjectOutlined',
    children: [
      { path: '/programs', title: 'project.title.programList', order: 1, perm: 'program-view' },
      { path: '/projects', title: 'project.title.list', order: 2, perm: 'project-view' },
      { path: '/executions', title: 'project.title.executions', order: 3, perm: 'execution-view' },
      { path: '/board-spaces', title: 'board.title.spaceList', order: 4, perm: 'board-view' },
    ],
  },
  {
    key: 'quality',
    title: 'nav.group.quality',
    icon: 'ExperimentOutlined',
    children: [{ path: '/libraries', title: 'quality.title.libraries', order: 1, perm: 'library-view' }],
  },
  {
    key: 'doc',
    title: 'nav.group.doc',
    icon: 'FileTextOutlined',
    children: [
      { path: '/doc/spaces', title: 'docSpace.title.list', order: 1, perm: 'doc-space-view' },
      { path: '/doc/my', title: 'doc.title.my', order: 2, perm: 'doc-view' },
      { path: '/doc/files', title: 'doc.title.files', order: 3, perm: 'doc-view' },
    ],
  },
  {
    key: 'org',
    title: 'nav.group.org',
    icon: 'TeamOutlined',
    children: [
      { path: '/org/accounts', title: 'org.accounts.title', order: 1, perm: 'account-view' },
      { path: '/org/departments', title: 'org.departments.title', order: 2, perm: 'department-view' },
      { path: '/personnel', title: 'personnel.title', order: 4, perm: 'personnel-view' },
      { path: '/personnel/workload', title: 'personnel.workload.title', order: 5, perm: 'personnel-view' },
    ],
  },
  {
    key: 'admin',
    title: 'nav.group.admin',
    icon: 'SettingOutlined',
    children: [
      { path: '/admin/settings', title: 'platform.settings.title', order: 1, perm: 'setting-manage' },
      {
        key: 'admin/lang',
        title: 'nav.section.adminLang',
        order: 2,
        children: [
          { path: '/admin/lang-items', title: 'platform.lang.title', order: 1, perm: 'lang-manage' },
          { path: '/admin/lang-upload', title: 'platform.langUpload.title', order: 2, perm: 'lang-manage' },
        ],
      },
      { path: '/settings/stages', title: 'stage.title.list', order: 3, perm: 'stage-view' },
      { path: '/admin/roles', title: 'org.role.title', order: 4, perm: 'role-view' },
      {
        key: 'admin/audit',
        title: 'nav.section.auditLog',
        order: 5,
        children: [
          { path: '/admin/audit-logs', title: 'platform.auditLog.title', order: 1, perm: 'audit-log-view' },
          { path: '/admin/login-logs', title: 'platform.loginLog.title', order: 2, perm: 'audit-log-view' },
        ],
      },
    ],
  },
]

/** 隐藏页 → 菜单高亮目标（06 A1-1）：详情/批量等上下文页的菜单归属。 */
export const activeMenuMap: Record<string, string> = {
  '/board-spaces/:boardSpaceId': '/board-spaces',
  '/boards/:boardId': '/board-spaces',
  '/bugs/:bugId': '/products',
  '/bugs/batch-edit': '/products',
  '/builds/:buildId': '/products',
  '/doc/spaces/:docSpaceId': '/doc/spaces',
  '/docs/:docId': '/doc/spaces',
  '/docs/:docId/diff': '/doc/spaces',
  '/docs/:docId/edit': '/doc/spaces',
  '/docs/:docId/versions': '/doc/spaces',
  '/executions/:executionId': '/executions',
  '/executions/:executionId/kanban': '/executions',
  '/executions/:executionId/reports': '/executions',
  '/executions/:executionId/reports/burn': '/executions',
  '/executions/:executionId/tasks': '/executions',
  '/executions/:executionId/tasks/batch-create': '/executions',
  '/libraries/:libraryId': '/libraries',
  '/libraries/:libraryId/test-cases/batch': '/libraries',
  '/my/profile': '/my',
  '/notifications/settings': '/notifications',
  '/org/accounts/:accountId': '/org/accounts',
  '/org/accounts/batch': '/org/accounts',
  '/org/groups/:groupId': '/admin/roles',
  '/org/groups/:groupId/privileges': '/admin/roles',
  '/plans/:planId': '/products',
  '/products/:productId': '/products',
  '/products/:productId/branches': '/products',
  '/products/:productId/bugs': '/products',
  '/products/:productId/bugs/batch': '/products',
  '/products/:productId/builds': '/products',
  '/products/:productId/categories': '/products',
  '/products/:productId/dynamic': '/products',
  '/products/:productId/plans': '/products',
  '/products/:productId/projects': '/products',
  '/products/:productId/releases': '/products',
  '/products/:productId/reports/bug-distribution': '/products',
  '/products/:productId/reports/story-summary': '/products',
  '/products/:productId/stories': '/products',
  '/products/:productId/stories/batch': '/products',
  '/products/:productId/suites': '/products',
  '/products/:productId/test-cases': '/products',
  '/products/:productId/test-cases/batch': '/products',
  '/products/:productId/test-runs': '/products',
  '/products/:productId/track': '/products',
  '/products/batch-edit': '/products',
  '/programs/:programId': '/programs',
  '/projects/:projectId': '/projects',
  '/projects/:projectId/executions': '/projects',
  '/projects/:projectId/members': '/projects',
  '/projects/:projectId/stakeholders': '/projects',
  '/projects/:projectId/stories': '/projects',
  '/projects/:projectId/weekly-report': '/projects',
  '/projects/:projectId/whitelist': '/projects',
  '/releases/:releaseId': '/products',
  '/reports/:reportId': '/executions',
  '/stories/:storyId': '/products',
  '/stories/batch-edit': '/products',
  '/suites/:suiteId': '/products',
  '/tasks/:taskId': '/executions',
  '/tasks/batch-edit': '/executions',
  '/test-cases/:caseId': '/products',
  '/test-cases/batch-edit': '/products',
  '/test-runs/:testRunId': '/executions',
  '/test-runs/:testRunId/cases': '/executions',
  '/test-runs/:testRunId/reports/case-pass-rate': '/executions',
  '/todos/:todoId': '/my/todos',
  '/todos/batch-create': '/my/todos',
  '/todos/batch-edit': '/my/todos',
}
