// 域出口白名单（01 §3.2）：跨域只准 import 本文件。

export type {
  ActivityPage,
  BatchCreateResultItem,
  BatchResultItem,
  BugView,
  ListResult,
  ReportView,
  ResultView,
  SuiteView,
  TestCaseView,
  TestRunView,
} from './api/quality.api'
export {
  fetchBug,
  fetchBugActivities,
  fetchBugMeta,
  fetchBugs,
  fetchExecutionReports,
  fetchLibraries,
  fetchLibrary,
  fetchLibraryCases,
  fetchReport,
  fetchReportMeta,
  fetchSuite,
  fetchSuiteMeta,
  fetchSuites,
  fetchTestCase,
  fetchTestCaseActivities,
  fetchTestCaseMeta,
  fetchTestCases,
  fetchTestRun,
  fetchTestRunActivities,
  fetchTestRunCases,
  fetchTestRunMeta,
  fetchTestRuns,
  patchReport,
  QUALITY_QUERY_ROOTS,
  qk,
  submitBatchBugs,
  submitBatchCreateBugs,
  submitBatchCreateTestCases,
  submitBatchTestCases,
  submitBug,
  submitLibrary,
  submitReport,
  submitSuite,
  submitTestCase,
  submitTestRun,
} from './api/quality.api'
export {
  actionI18nKey,
  activateAssigneeFallback,
  BUG_SEVERITIES,
  bugTone,
  canPatchStatus,
  closeDateError,
  MAX_STEPS,
  normalizeSteps,
  REPORT_IMMUTABLE_FIELDS,
  requiresDuplicateOf,
  requiresResolvedBuild,
  reviewAllowed,
  runResultTone,
  STEP_TEXT_MAX,
  SUITE_TYPES,
  severityKey,
  suiteTone,
  summarizeResults,
  TEST_CASE_MARKER_STATUSES,
  TEST_CASE_RESULTS,
  TEST_RUN_RESULTS,
  testCaseTone,
  testRunTone,
  validateSteps,
} from './model'
