// 域出口白名单（01 §3.2）：跨域只准 import 本文件。

export type {
  AccountOption,
  ActivityPage,
  ActivityView,
  BatchCreateResultItem,
  BugDistributionReport,
  BugView,
  BurnReport,
  CasePassRateReport,
  ListResult,
  MySummaryView,
  StorySummaryReport,
  StoryView,
  TaskView,
  TodoAction,
  TodoView,
  WeeklyReportView,
} from './api/workspace.api'
export {
  fetchAccountOptions,
  fetchBugDistributionReport,
  fetchBurnReport,
  fetchCasePassRateReport,
  fetchMyActivities,
  fetchMyBugs,
  fetchMyStories,
  fetchMySummary,
  fetchMyTasks,
  fetchSettings,
  fetchStorySummaryReport,
  fetchTodo,
  fetchTodoMeta,
  fetchTodos,
  fetchTodoTypes,
  fetchWeeklyReport,
  qk,
  runTodoAction,
  saveSettings,
  searchObjects,
  submitBatchTodos,
  submitTodo,
  WORKSPACE_QUERY_ROOTS,
} from './api/workspace.api'
export type { ReportChartProps } from './components/report-chart'
export { default as ReportChart } from './components/report-chart'
export {
  activityDateKey,
  addDays,
  analysisLines,
  barOption,
  bugDistributionGroups,
  burnOption,
  type ChartPoint,
  caseResultPoints,
  DASHBOARD_LAYOUT_KEY,
  DASHBOARD_WIDGETS,
  type DashboardLayoutItem,
  type DashboardWidgetKind,
  type DashboardWidgetSize,
  DEFAULT_MY_ROLE,
  type DistributionPoint,
  defaultDashboardLayout,
  donutOption,
  groupActivitiesByDate,
  isDefaultDashboardLayout,
  localizedPoints,
  MY_ROLES,
  type MyListKind,
  mondayOf,
  myRoleKey,
  normalizeDateTab,
  normalizeMyRole,
  parseDashboardLayout,
  patchDashboardLayout,
  reorderDashboardLayout,
  type StorySummaryGroups,
  shiftWeek,
  stackedBarOption,
  storySummaryGroups,
  TODO_BATCH_MAX_ROWS,
  TODO_DATE_TABS,
  TODO_PRIORITIES,
  TODO_STATUSES,
  type TodoBatchOutcome,
  type TodoBatchRow,
  type TodoCreateValues,
  type TodoDateTab,
  type TodoEditValues,
  todayIso,
  todoBatchItems,
  todoBatchOutcomes,
  todoCreateBody,
  todoDateFilter,
  todoDisplayTitle,
  todoObjectRequired,
  todoObjectScope,
  todoPatchBody,
  todoPriorityKey,
  todoStatusKey,
  todoStatusTone,
  todoTypeKey,
  visibleDashboardLayout,
} from './model'
